### ISSUE TITLE
Make the tests self-contained

### ISSUE THREAD

**Issue by goloroden** [sealsystems/node-mongo#2]
Hi there 😊 

Right now, the tests are not self-contained, as you manually need to start a MongoDB that the tests can connect to.

It would be great if starting and stopping an appropriate MongoDB with the correct setup could be done automatically by the tests, similar to e.g. the tests of the [sparbuch](https://github.com/thenativeweb/sparbuch/blob/9ddd2ac297df0873e0f1ee87634395748d46c405/test/units/pre.js) module.

**Comment by seal-ss** [comment]
There's no official Windows container version of `mongo` (well, there was one three months ago), so an implicit `docker run mongo` won't work on AppVeyor for our Windows CI pipeline.

**Comment by StefanScherer** [comment]
Maybe `mongo-unit` could be a thing. https://www.toptal.com/nodejs/integration-and-e2e-tests-nodejs-mongodb

Or looking at how the `mongodb` package is tested ([devDependencies in package.json](https://github.com/mongodb/node-mongodb-native/blob/e62e5c93e6f0e3f76bd68c9aef48844c9bbae771/package.json#L30-L31) show `mongodb-mock-server` and `mongodb-test-runner`.

**Comment by StefanScherer** [comment]
`mongo-unit` uses  `mongodb-prebuilt` which "Works on Mac, Windows, Linux and Solaris OSes that MongoDB supports."

**Comment by StefanScherer** [comment]
[`mongodb-runner`](https://www.npmjs.com/package/mongodb-runner) from the mongodb-js org also works for Linux and Windows.

**Comment by StefanScherer** [comment]
The bigger problem is that these tests depend on a Docker image plossys/mongodb that has TLS enabled by default. So using the official `mongo` image or the `mongodb-runner` rail in some tests.
We have to adjust these tests to make the tests work for the community. :-)

**Comment by StefanScherer** [comment]
Hi Golo, `npm run test` works pretty fine now with PR #5, but `bot` or `npm run bot` doesn't seem to take care for the `pretest` and `posttest` entries in `package.json`  😁

**Comment by seal-mis** [comment]
Thank you very much for your suggestion! 😃

In the next couple of weeks, we have to update our build configuration for CircleCI. This will be the perfect opportunity to also rework the test setup.

I created an internal issue and close this one to prevent duplicates.
