### ISSUE TITLE
Can we remove sort criteria in query to support CosmosDB?

### ISSUE THREAD

**Issue by seal-ss** [sealsystems/node-mongo#3]
I tried this module with Azure CosmosDB, but got an error.

<img width="1440" alt="bildschirmfoto 2018-04-03 um 15 06 13" src="https://user-images.githubusercontent.com/8137307/38251325-6fe032c4-3751-11e8-89f8-3db7e407fde3.png">

Can we remove this sort criteria at https://github.com/sealsystems/node-mongo/blob/ff7f27c809e857cce76843607231fb9bc865e06f/lib/mongo.js#L53

The file that we search has a unique fileName (UUID) and "there can be only one".

When I remove that criteria everything looks fine in CosmosDB and the file meta data can be updated after that find().

<img width="1440" alt="bildschirmfoto 2018-04-03 um 15 05 55" src="https://user-images.githubusercontent.com/8137307/38251444-c211eb0a-3751-11e8-8644-539ee2a68c4e.png">

**Comment by StefanScherer** [comment]
Fixed with #4, version 2.1.9
